### ISSUE TITLE
Unknown CMake command "bundle_param"

### ISSUE THREAD

**Issue by Astalaseven** [fw4spl-org/fw4spl-ar#1]
Hi,

I just tried to compile `fw4spl` but I'm stuck at the configuration part.
I grepped `bundle_param` in the project folder and looked on Google but it doesn't seem to exist except in those 2 files:

```sh
~/FW4SPL> grep "bundle_param" -R .
./Dev/fw4spl-ar/Apps/ARCalibration/Properties.cmake:bundle_param(appXml PARAM_LIST config parameters PARAM_VALUES ARCalibrationBase ARCalibrationAppBase)
./Dev/fw4spl-ar/Apps/VideoTracking/Properties.cmake:bundle_param(appXml PARAM_LIST config PARAM_VALUES VideoTracking)
```

Could you help me out?

I tried both `master` and `fw4spl_0.10.2` branches.

```sh
~/FW4SPL/Dev/fw4spl> cmake CMakeLists.txt
CMake Error at /home/asta/FW4SPL/Dev/fw4spl-ar/Apps/ARCalibration/Properties.cmake:43 (bundle_param):
  Unknown CMake command "bundle_param".
Call Stack (most recent call first):
  CMakeLists.txt:537 (include)
  CMakeLists.txt:639 (loadProperties)

```

**Comment by schweitzer** [comment]
Hi,
To resolve this error you have to apply "un-reviewed" commit (called patches) on fw4spl repository.
To ensure that you have latest developpement version of fw4spl, please follow the steps described in this article https://fw4spl-org.github.io/fw4spl-blog/2015/07/15/Development-status-v0102.html

**Comment by Astalaseven** [comment]
Thanks for your answer, but it hadn't a lot of chance of success.
```
hg qclone ssh://hg@bitbucket.org/fw4splorg/fw4spl-patches
remote: Permission denied (publickey).
abandon : no suitable response from remote hg !
```

It works better with: `hg qclone https://bitbucket.org/fw4splorg/fw4spl-patches`

**Comment by fbridault** [comment]
Modified the blog post to use https instead of ssh.
